title: ヤロミル
email: author@jaromiru.com
description: MACHINE LEARNING & AI
author: Jaromír Janisch
baseurl: "" 
url: "https://jaromiru.com" 
date_format: "%-d %B, %Y"

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Theme options
enable_mathjax: true
disqus_shortname: jaromiru-com

# plugins:
  # - jekyll-feed


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
