title: ヤロミル
email: email@example.com
description: Things to do
author: sourjyo
baseurl: "" 
url: "https://sourjyo0.github.com/write" 
date_format: "%-d %B, %Y"

# Build settings
markdown: kramdown
permalink: /write/:year/:month/:day/:title/
theme: minima
# Theme options
enable_mathjax: true
#disqus_shortname: 

# plugins:
  # - jekyll-feed


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
